version: '3.8'
services:
  tsfs_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TSFSBackendDB
    # volumes:
    #  - ./.postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    networks:
      - tsfs_net
  tsfs_backend:
    image: openjdk:17
    volumes:
      - ./build/libs/TSFSBackend5.jar:/app/TSFSBackend5.jar
    networks:
      - tsfs_net
    working_dir: /app/
    command: java -jar /app/TSFSBackend5.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tsfs_db:5432/TSFSBackendDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 8080:8080
    #      - 5005:5005
    depends_on:
      - tsfs_db
    restart: always
networks:
  tsfs_net:
    driver: bridge